# Generated by Django 6.1 on 2026-08-31 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LojaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Acessórios de celular', max_length=80, verbose_name='Nome da loja')),
                ('whatsapp', models.CharField(default='5511999999999', max_length=20, verbose_name='WhatsApp (DDI+DDD+número)')),
                ('pix_key', models.CharField(blank=True, max_length=120, verbose_name='Chave Pix')),
                ('suporte_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail de suporte')),
                ('suporte_horario', models.CharField(default='Seg–Sáb, 9h às 18h', max_length=80, verbose_name='Horário de atendimento')),
            ],
            options={
                'verbose_name': 'Configuração da loja',
                'verbose_name_plural': 'Configuração da loja',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('capas', 'Capinhas'), ('peliculas', 'Películas'), ('audio', 'Áudio'), ('energia', 'Energia'), ('suportes', 'Suportes')], default='capas', max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('preco_antigo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço antigo')),
                ('promocao_ativa', models.BooleanField(default=False, verbose_name='Em promoção')),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço promocional')),
                ('selo_promo', models.CharField(blank=True, max_length=40, verbose_name='Selo da promoção')),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('compat', models.CharField(blank=True, max_length=80, verbose_name='Compatibilidade')),
                ('descricao', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='produtos/', verbose_name='Foto do produto')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TicketSuporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('assunto', models.CharField(max_length=120)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('andamento', 'Em andamento'), ('resolvido', 'Resolvido')], default='novo', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ticket de suporte',
                'verbose_name_plural': 'Tickets de suporte',
                'ordering': ['-criado_em'],
            },
        ),
    ]
